### ISSUE TITLE
ESWD16

### ISSUE THREAD

**Issue by cjmccarty66** [d21spike/etekcity#2]
I am using hass.io and it the add-on is not finding the ESWD16

**Comment by d21spike** [comment]
@cjmccarty66 My setup runs home assistant in a docker but I can't image it being much different from hass.io. I just pushed some changes to improve logging so hopefully we can things working for you. **The logging changes should help us figure out where you're getting stuck.**

First let's verify your installation is as below, **inside custom_components directory** maintaining folder structure as in this repo.
![image](https://user-images.githubusercontent.com/6399602/85316968-9ca90d80-b48b-11ea-959a-6111a03b79ed.png)

Next in your configuration, under **light:** your settings should be similar to below.
![image](https://user-images.githubusercontent.com/6399602/85317186-f8739680-b48b-11ea-93a6-0d8b576719a0.png)

Lastly, to log your settings should be similar to below. Keeping default at critical and etekcity at info will give you the most information.
![image](https://user-images.githubusercontent.com/6399602/85317267-21942700-b48c-11ea-8c8d-a6d31a937d88.png)

Once Home Assistant is restarted, under Developer Tools -> Logs -> Load Full Home Assistant Log ... your output should be similar to below.
![image](https://user-images.githubusercontent.com/6399602/85318179-89973d00-b48d-11ea-8f27-0093f5257bff.png)

Make note of the device Name, in my case **Sunroom**. At this point this will be used to add a Home Assistant card.
![image](https://user-images.githubusercontent.com/6399602/85317993-450ba180-b48d-11ea-934d-5e553531b0c3.png)

This information is valid as of the following Home Assistant version
![image](https://user-images.githubusercontent.com/6399602/85318699-6faa2a00-b48e-11ea-9bd0-9fbccf6b48da.png)

**Comment by cjmccarty66** [comment]
This is the error I am getting  now
Logger: homeassistant.core
Source: custom_components/etekcity/required/etekcity.py:2
First occurred: 6:19:13 PM (5 occurrences)
Last logged: 6:19:13 PMError doing job: Task exception was never retrievedTraceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 780, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 780, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 55, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 151, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 273, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/etekcity/light.py", line 1, in <module>
    from .required.etekcity import EtekCity
  File "/config/custom_components/etekcity/required/etekcity.py", line 2, in <module>
    from .eswd16 import ESWD16
  File "/config/custom_components/etekcity/required/eswd16.py", line 33
    account_info = {}
                    ^
TabError: inconsistent use of tabs and spaces in indentation

-----Original Message-----

**Comment by d21spike** [comment]
@cjmccarty66 Ahh that's what I get for copying code out of Putty. Indentation error, I'll try to push a fix tomorrow morning.

**Comment by d21spike** [comment]
Well I looked over the code and even tried running a replace (multiple ways), not seeing any mixing of tabs and spaced. So this may be the way you copied it.

![image](https://user-images.githubusercontent.com/6399602/85398901-e1808300-b523-11ea-86cf-81231c048fdc.png)

You can try manually fixing the error, just replacing any potential tabs with spaces. . I guess the better question is how are you installing this custom_component?

**Comment by cjmccarty66** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 190, in async_load_platform
    setup_success = await setup.async_setup_component(hass, component, hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 780, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 780, in async_forward_entry_setup
    result = await async_setup_component(self.hass, domain, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 49, in async_setup_component
    return await setup_tasks[domain]  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 55, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 151, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 273, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/etekcity/light.py", line 1, in <module>
    from .required.etekcity import EtekCity
  File "/config/custom_components/etekcity/required/etekcity.py", line 6
    account_id = ''
             ^
IndentationError: expected an indented block

**Comment by cjmccarty66** [comment]
Error while setting up etekcity platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/etekcity/light.py", line 41, in setup_platform
    etek = EtekCity(email, password)
TypeError: EtekCity() takes no arguments

**Comment by d21spike** [comment]
As you can see the EtekCity() constructor **__init__** does indeed take two arguments, email and password. I would verify your indentation is as in the original file. In a python class, all member functions are indented, as seen below "def __init__(self, email, password):" has 4 spaces before it. If they lack the indentation, the function no longer belongs to the class so in this case EtekCity would be assigned a default constructor like this "def __init__(self):" which takes no arguments.

![image](https://user-images.githubusercontent.com/6399602/85409683-1c8ab280-b534-11ea-968e-956e8dc5f23a.png)

**Comment by cjmccarty66** [comment]
Thank you For your help
